### ISSUE TITLE
Motor mounts in CAD as well as exported STL are not usable due to a section that blocks belt path

### ISSUE THREAD

**Issue by sakitume** [timwieder1509/CoreCubeXY#1]
![image](https://github.com/timwieder1509/CoreCubeXY/assets/875866/95d5fcf7-9be3-46dc-a8ba-3dc1d8318792)

If you look at the video, you'll see the belt on let side goes from left/front idler all the way through the motor mount onto the pulley on the motor. The motor mount is different in the video compared to the one provided as an exported `.stl` as well as what is in the `.step` file.

![image](https://github.com/timwieder1509/CoreCubeXY/assets/875866/9623f8c8-470d-47a3-ad4b-f2340bc4dcb4)

**Comment by sakitume** [comment]
I don't know if this is a real issue or not, but I couldn't understand how the belt would be able to run from the front idler to the motor pulley. So I removed that piece and made a separate spacer with an OD of 8mm and an ID of 5.4mm and is 8.2mm tall. I will use a 0.5mm shim between the spacer and the pulley so that it can spin freely without binding against the spacer.

![image](https://github.com/timwieder1509/CoreCubeXY/assets/875866/abdfbbfc-7631-4be8-8aec-23c1f596e577)

After I print out the new pieces I will let you know if that worked for me or not.

**Comment by timwieder1509** [comment]
Hi,

Yes you are right, i have to change that, it seems like i have uploaded an old version of this part. Thanks for letting me know! I also worked with separate spacers on my printer.
________________________________
Von: sakitume ***@***.***>
Gesendet: Monday, July 24, 2023 9:24:43 AM
An: timwieder1509/CoreCubeXY ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [timwieder1509/CoreCubeXY] Motor mounts in CAD as well as exported STL are not usable due to a section that blocks belt path (Issue #1)


I don't know if this is a real issue or not, but I couldn't understand how the belt would be able to run from the front idler to the motor pulley. So I removed that piece and made a separate spacer with an OD of 8mm and an ID of 5.4mm and is 8.2mm tall. I will use a 0.5mm shim between the spacer and the pulley so that it can spin freely without binding against the spacer.

[image]<https://user-images.githubusercontent.com/875866/255515323-abdfbbfc-7631-4be8-8aec-23c1f596e577.png>

After I print out the new pieces I will let you know if that worked for me or not.

**Comment by sakitume** [comment]
Ah, thanks for confirming. The spacer I made seems to be a good fit (in conjunction with the 0.5mm shim I have). I'll know for sure once I'm able to actually tension the belts.

I've said this a few times, but I really like the belt pathing you've chosen and how you're able to reduce the pulley count to the bare minimum; similar designs I've come across need two additional pulleys per motor.

Really looking forward to testing out the X/Y motion system soon.

**Comment by timwieder1509** [comment]
Thank you for your comment and the positive response to my project. I very am glad to see that you like my design. I fixed the issue and added a spacer to the files.
